---
title: Getting my bearings
output:
  pdf_document:
    df_print: kable
---

```{r setup}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

{
  library(tidyverse)
  library(broom)
  library(haven)
  library(margins)
  library(sjlabelled)
  library(sjPlot)
  library(stargazer)
}


```


Just working through the do file in order

https://www-journals-uchicago-edu.ezp-prod1.hul.harvard.edu/doi/pdf/10.1086/711133
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/9ERCTY

```{r party_oil}

working_wide <- read_dta("replication_data/working_wide.dta")

working_wide %>% 
  lm(oil ~ pidr, data = .)

```

```{r table_1}

working_long <- read_dta("replication_data/working_long.dta") 
  
mod1 <- working_long %>% 
  filter(independent == 0,
         issue2 == 1) %>% 
  lm(rum ~ consis * rep_i, data = .) 

mod2 <- working_long %>% 
  filter(nonlean == 1,
         issue2 == 1) %>% 
  lm(rum ~ consis * rep_i, data = .) 

mod3 <- working_long %>% 
  filter(independent == 0,
         issue2 == 2) %>% 
  lm(rum ~ consis * rep_i, data = .) 

mod4 <- working_long %>% 
  filter(nonlean == 1,
         issue2 == 2) %>% 
  lm(rum ~ consis * rep_i, data = .) 

mod5 <- working_long %>% 
  filter(independent == 0) %>% 
  lm(rum ~ consis * rep_i + as_factor(issue2), data = .) 

mod6 <- working_long %>% 
  filter(nonlean == 1) %>% 
  lm(rum ~ consis * rep_i + as_factor(issue2), data = .) 

stargazer(mod1, mod2, mod3, mod4, mod5, mod6,
          show.ci = FALSE,
          show.se = TRUE,
          p.style = "stars",
          collapse.se = TRUE,
          pred.labels = c("Intercept", 
                          "Party-Consistent = 1", 
                          "Republican = 1", 
                          "Consistent * Republican",
                          "Wisconsin = 1"),
          dv.labels = c("Ohio", "Ohio", "Wisconsin", "Wisconsin",
                        "Pooled", "Pooled"),
          title = "Table 1: Democrats and Republicans are Equally Subject to Consistency Pressures",
          digits = 3)

```

```{r plot_for_table_1}

# not part of the actual study, but thought it would be good to visualize

working_long %>% 
  mutate(consis = as_factor(consis)) %>% 
  drop_na(consis, rep_i) %>% 
  ggplot(aes(rep_i, rum)) +
  geom_jitter(aes(color = consis), alpha = 0.5, width =) +
  geom_smooth(method = "lm", color = "black") +
  theme_classic() +
  labs(x = "Republican?",
       y = "Belief in rumor",
       title = "Neither party exhibited greater proclivity to believe false rumors") +
  scale_x_continuous(breaks = c(0, 1),
                     labels = c(0, 1)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("Definitely did not occur", 
                                "Probably occurred",
                                "Might have occurred",
                                "Probably did not occur",
                                "Definitely occurred")) +
  scale_color_manual(labels = c("Inconsistent with party",
                                "Consistent with party"),
                     values = c("lightblue", "navyblue"))

ggsave("replication_figures/table1_plot.jpeg")
```


```{r section_6}

# SI Section 6: text-based claims

study2_long <- read_dta("replication_data/study2_long.dta") %>% 
    mutate(consis = as_factor(consis),
           rep_i = as_factor(rep_i),
           positly = as_factor(positly),
           isuse = as_factor(issue))

study2_long %>% 
  filter(independent == 0,
         issue == "_ohio") %>% 
  lm(rum ~ as_factor(consis) * rep_i * positly, data = .)

study2_long %>% 
  filter(independent == 0,
         issue == "_wisc") %>% 
  lm(rum ~ as_factor(consis) * rep_i * positly, data = .)

```

# **NOT SURE HOW TO MAKE MARGINAL EFFECT WORK**

```{r table_si2}

# continuing to work through do file

{
  mod1 <- study2_long %>% 
  filter(independent == 0,
         issue == "_ohio") %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
  
  mod2 <- study2_long %>% 
    filter(nonlean == 1,
           issue == "_ohio") %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
}

{
  mod3 <- study2_long %>% 
    filter(independent == 0,
           issue == "_wisc") %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
  
  mod4 <- study2_long %>% 
    filter(nonlean == 1,
           issue == "_wisc") %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
}

{
  mod5 <- study2_long %>% 
    filter(independent == 0,
           issue %in% c("_wisc", "_ohio")) %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
  
  # do margins
  
  mod6 <- study2_long %>% 
    filter(nonlean == 1,
           issue %in% c("_wisc", "_ohio")) %>% 
    lm(rum ~ consis * rep_i + positly, data = .)
}

# getting output table, modifying code for other table

####################################################
########## THIS DOES NOT MATCH UP ##################
# are her values truncated?
####################################################

stargazer(mod1, mod2, mod3, mod4, mod5, mod6,
          show.ci = FALSE,
          show.se = TRUE,
          p.style = "stars",
          collapse.se = TRUE,
          pred.labels = c("Intercept",
                          "Party-Consistent = 1",
                          "Republican = 1",
                          "Positly = 1",
                          "Consistent * Republican"),
          dv.labels = c("Ohio", "Ohio", "Wisconsin", "Wisconsin",
                        "Pooled", "Pooled"),
          title = "Table SI-2: Results from Replication Study",
          digits = 3)


```

```{r si_section_6}

# SI section 6, text-based claims

study2_long %>% 
  filter(independent == 0,
         issue %in% c("_incomp1", "_incomp2")) %>% 
  lm(rum ~ consis * rep_i + issue2 + acq_comb, data = .)

study2_long %>% 
  filter(independent == 0,
         issue %in% c("_hyp1", "_hyp2")) %>% 
  lm(rum ~ consis * rep_i + issue2 + acq_comb, data = .)

study2_long %>% 
  filter(independent == 0,
         issue %in% c("_breach1", "_breach2")) %>% 
  lm(rum ~ consis * rep_i + issue2 + acq_comb, data = .)

```

```{r table_si3}

mod1 <- working_long %>% 
  filter(ideology2 != 4,
         issue2 == 1) %>% 
  lm(rum ~ iconsis * cons_i, data = .)

mod2 <- working_long %>% 
  filter(ideology2 != 4,
         issue2 == 2) %>% 
  lm(rum ~ iconsis * cons_i, data = .)

mod3 <- working_long %>% 
  filter(ideology2 != 4) %>% 
  lm(rum ~ iconsis * cons_i + issue2, data = .)

# displaying in a nice regression table

stargazer(mod1, mod2, mod3,
          show.ci = FALSE,
          show.se = TRUE,
          collapse.se = TRUE,
          p.style = "stars",
          pred.labels = c("Intercept", "Ideology-consistent = 1",
                          "Conservative = 1", "Consistent * Conservative",
                          "Wisconsin = 1"),
          dv.labels = c("Ohio", "Wisconsin", "Pooled"),
          title = "Table SI-3: Ideology Does not Moderate Consistency Effects",
          digits = 3)

```

```{r table_si4}

mod1 <- study2_long %>% 
  filter(ideology2 != 4,
         issue == "_ohio") %>% 
  lm(rum ~ iconsis * cons_i, data = .)

mod2 <- study2_long %>% 
  filter(ideology2 != 4,
         issue == "_wisc") %>% 
  lm(rum ~ iconsis * cons_i, data = .)

mod3 <- study2_long %>% 
  filter(ideology2 != 4,
         issue %in% c("_wisc", "_ohio")) %>% 
  lm(rum ~ iconsis * cons_i + issue, data = .)

stargazer(mod1, mod2, mod3,
          show.ci = FALSE,
          show.se = TRUE,
          collapse.se = TRUE,
          p.style = "stars",
          pred.labels = c("Intercept", "Ideology-consistent = 1",
                          "Conservative = 1", "Consistent * Conservative",
                          "Wisconsin = 1"),
          dv.labels = c("Ohio", "Wisconsin", "Pooled"),
          title = "Table SI-4: Ideology and Consistency in Study 2",
          digits = 3)

```

```{r table_si5}



```

